# This workflow will test and deploy the project code
# It will run whenever there are any pushed changes to the main branch

name: Test-Deploy-VA
on:
  - push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: hello-world
        run: echo "Hello VariousArtists!"